---
name: Publish html

on:
  push:
    branches:
    - master

jobs:
  publish:
    name: Publish github pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: npm install
        run: npm install
      - name: build html
        run: npm run build
      - name: deploy on github pages
        uses: peaceiris/actions-gh-pages@v2.4.0
        if: success()
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
